/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as lendingPoolSol from "./LendingPool.sol";
export type { lendingPoolSol };
export type { TrustScore } from "./TrustScore";
