/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace LendingPool {
  export type LoanStruct = {
    id: BigNumberish;
    borrower: AddressLike;
    lender: AddressLike;
    amount: BigNumberish;
    interest: BigNumberish;
    duration: BigNumberish;
    collateralToken: AddressLike;
    collateralAmount: BigNumberish;
    startTime: BigNumberish;
    funded: boolean;
    repaid: boolean;
    defaulted: boolean;
  };

  export type LoanStructOutput = [
    id: bigint,
    borrower: string,
    lender: string,
    amount: bigint,
    interest: bigint,
    duration: bigint,
    collateralToken: string,
    collateralAmount: bigint,
    startTime: bigint,
    funded: boolean,
    repaid: boolean,
    defaulted: boolean
  ] & {
    id: bigint;
    borrower: string;
    lender: string;
    amount: bigint;
    interest: bigint;
    duration: bigint;
    collateralToken: string;
    collateralAmount: bigint;
    startTime: bigint;
    funded: boolean;
    repaid: boolean;
    defaulted: boolean;
  };
}

export interface LendingPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkDefault"
      | "createLoanRequest"
      | "fundLoan"
      | "getLoan"
      | "loans"
      | "nextLoanId"
      | "owner"
      | "renounceOwnership"
      | "repayLoan"
      | "transferOwnership"
      | "trustScoreContract"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "LoanCreated"
      | "LoanDefaulted"
      | "LoanFunded"
      | "LoanRepaid"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkDefault",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createLoanRequest",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      AddressLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "fundLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "loans", values: [BigNumberish]): string;
  encodeFunctionData(
    functionFragment: "nextLoanId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "repayLoan",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "trustScoreContract",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkDefault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createLoanRequest",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "fundLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLoan", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "loans", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextLoanId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "repayLoan", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "trustScoreContract",
    data: BytesLike
  ): Result;
}

export namespace LoanCreatedEvent {
  export type InputTuple = [
    loanId: BigNumberish,
    borrower: AddressLike,
    amount: BigNumberish,
    collateralToken: AddressLike,
    collateralAmount: BigNumberish
  ];
  export type OutputTuple = [
    loanId: bigint,
    borrower: string,
    amount: bigint,
    collateralToken: string,
    collateralAmount: bigint
  ];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
    amount: bigint;
    collateralToken: string;
    collateralAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanDefaultedEvent {
  export type InputTuple = [loanId: BigNumberish];
  export type OutputTuple = [loanId: bigint];
  export interface OutputObject {
    loanId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanFundedEvent {
  export type InputTuple = [loanId: BigNumberish, lender: AddressLike];
  export type OutputTuple = [loanId: bigint, lender: string];
  export interface OutputObject {
    loanId: bigint;
    lender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LoanRepaidEvent {
  export type InputTuple = [loanId: BigNumberish, borrower: AddressLike];
  export type OutputTuple = [loanId: bigint, borrower: string];
  export interface OutputObject {
    loanId: bigint;
    borrower: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LendingPool extends BaseContract {
  connect(runner?: ContractRunner | null): LendingPool;
  waitForDeployment(): Promise<this>;

  interface: LendingPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkDefault: TypedContractMethod<
    [_loanId: BigNumberish],
    [void],
    "nonpayable"
  >;

  createLoanRequest: TypedContractMethod<
    [
      _amount: BigNumberish,
      _duration: BigNumberish,
      _interest: BigNumberish,
      _collateralToken: AddressLike,
      _collateralAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  fundLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  getLoan: TypedContractMethod<
    [_loanId: BigNumberish],
    [LendingPool.LoanStructOutput],
    "view"
  >;

  loans: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        borrower: string;
        lender: string;
        amount: bigint;
        interest: bigint;
        duration: bigint;
        collateralToken: string;
        collateralAmount: bigint;
        startTime: bigint;
        funded: boolean;
        repaid: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;

  nextLoanId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  repayLoan: TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  trustScoreContract: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkDefault"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createLoanRequest"
  ): TypedContractMethod<
    [
      _amount: BigNumberish,
      _duration: BigNumberish,
      _interest: BigNumberish,
      _collateralToken: AddressLike,
      _collateralAmount: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "fundLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "getLoan"
  ): TypedContractMethod<
    [_loanId: BigNumberish],
    [LendingPool.LoanStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "loans"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        string,
        bigint,
        bigint,
        boolean,
        boolean,
        boolean
      ] & {
        id: bigint;
        borrower: string;
        lender: string;
        amount: bigint;
        interest: bigint;
        duration: bigint;
        collateralToken: string;
        collateralAmount: bigint;
        startTime: bigint;
        funded: boolean;
        repaid: boolean;
        defaulted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextLoanId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "repayLoan"
  ): TypedContractMethod<[_loanId: BigNumberish], [void], "payable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "trustScoreContract"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "LoanCreated"
  ): TypedContractEvent<
    LoanCreatedEvent.InputTuple,
    LoanCreatedEvent.OutputTuple,
    LoanCreatedEvent.OutputObject
  >;
  getEvent(
    key: "LoanDefaulted"
  ): TypedContractEvent<
    LoanDefaultedEvent.InputTuple,
    LoanDefaultedEvent.OutputTuple,
    LoanDefaultedEvent.OutputObject
  >;
  getEvent(
    key: "LoanFunded"
  ): TypedContractEvent<
    LoanFundedEvent.InputTuple,
    LoanFundedEvent.OutputTuple,
    LoanFundedEvent.OutputObject
  >;
  getEvent(
    key: "LoanRepaid"
  ): TypedContractEvent<
    LoanRepaidEvent.InputTuple,
    LoanRepaidEvent.OutputTuple,
    LoanRepaidEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "LoanCreated(uint256,address,uint256,address,uint256)": TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;
    LoanCreated: TypedContractEvent<
      LoanCreatedEvent.InputTuple,
      LoanCreatedEvent.OutputTuple,
      LoanCreatedEvent.OutputObject
    >;

    "LoanDefaulted(uint256)": TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;
    LoanDefaulted: TypedContractEvent<
      LoanDefaultedEvent.InputTuple,
      LoanDefaultedEvent.OutputTuple,
      LoanDefaultedEvent.OutputObject
    >;

    "LoanFunded(uint256,address)": TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;
    LoanFunded: TypedContractEvent<
      LoanFundedEvent.InputTuple,
      LoanFundedEvent.OutputTuple,
      LoanFundedEvent.OutputObject
    >;

    "LoanRepaid(uint256,address)": TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;
    LoanRepaid: TypedContractEvent<
      LoanRepaidEvent.InputTuple,
      LoanRepaidEvent.OutputTuple,
      LoanRepaidEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
