/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITrustScore,
  ITrustScoreInterface,
} from "../../../contracts/LendingPool.sol/ITrustScore";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getScore",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
      {
        internalType: "int256",
        name: "change",
        type: "int256",
      },
    ],
    name: "updateScore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITrustScore__factory {
  static readonly abi = _abi;
  static createInterface(): ITrustScoreInterface {
    return new Interface(_abi) as ITrustScoreInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITrustScore {
    return new Contract(address, _abi, runner) as unknown as ITrustScore;
  }
}
